
### GET request with a header
GET http://localhost:8080/books
Accept: application/json
#Authorization: Basic admin 123

### GET request with a header
GET http://localhost:8080/books/1
Accept: application/json
Authorization: Basic admin 123

### GET request with a by name
GET http://localhost:8080/books?name=atomic
Accept: application/json
Authorization: Basic admin 123

### GET request with a by authors
GET http://localhost:8080/books?authors=james
Accept: application/json
Authorization: Basic admin 123

### GET request with a by name and authors
GET http://localhost:8080/books?name=atomic&authors=james
Accept: application/json
Authorization: Basic admin 123

### Send POST request with book1
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic admin 123

{
  "name": "atomic habits",
  "authors": "james clear",
  "publisher": "macmillian",
  "yearOfPublication": 2000,
  "summary": "good book"
}

### Send POST request with book2
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic admin 123

{
  "name": "atomic habits 2",
  "authors": "james clear",
  "publisher": "macmillian",
  "yearOfPublication": 2000,
  "summary": "good book"
}
### Send POST request with book3
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic admin 123

{
  "name": "crime and punishment",
  "authors": "dostoievisk",
  "publisher": "trinta e tres",
  "yearOfPublication": 1800,
  "summary": "Excelent book",
  "format": "PDF"
}

### DELETE request with a header
DELETE http://localhost:8080/books/14
Authorization: Basic admin 123

### PUT request with a header
PUT http://localhost:8080/books/2
Content-Type: application/json
Authorization: Basic admin 123

{
  "name": "crime and punishment updated",
  "authors": "dostoievisk",
  "publisher": "trinta e tres",
  "yearOfPublication": 1899,
  "summary": "Excelent book"
}


### GET request book-inventories
GET http://localhost:8080/book-inventories
Accept: application/json
Authorization: Basic admin 123

### Send POST request with boo1Inventory
POST http://localhost:8080/book-inventories
Content-Type: application/json
Authorization: Basic admin 123

{
 "bookId": 12,
 "quantity": 10
}

### DELETE request with a book-inventories
DELETE http://localhost:8080/book-inventories/13
Authorization: Basic admin 123