### GET request with a header
GET http://localhost:8080/books
Accept: application/json

### Send POST request with book1
POST http://localhost:8080/books
Content-Type: application/json

{
  "name": "atomic habits",
  "authors": "james clear",
  "publisher": "macmillian",
  "yearOfPublication": 2000,
  "summary": "good book"
}

### Send POST request with book2
POST http://localhost:8080/books
Content-Type: application/json

{
  "name": "crime and punishment",
  "authors": "dostoievisk",
  "publisher": "trinta e tres",
  "yearOfPublication": 1800,
  "summary": "Excelent book",
  "format": "PDF"
}

### DELETE request with a header
DELETE http://localhost:8080/books/14

### PUT request with a header
PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "name": "crime and punishment updated",
  "authors": "dostoievisk",
  "publisher": "trinta e tres",
  "yearOfPublication": 1899,
  "summary": "Excelent book"
}


### GET request book-inventories
GET http://localhost:8080/book-inventories
Accept: application/json

### Send POST request with boo1Inventory
POST http://localhost:8080/book-inventories
Content-Type: application/json

{
 "bookId": 12,
 "quantity": 10
}

### DELETE request with a book-inventories
DELETE http://localhost:8080/book-inventories/14